### ISSUE TITLE
dp2 v2 服务器模块升级后 dp2OPAC 模块报错

### ISSUE THREAD

**Issue by DigitalPlatform** [DigitalPlatform/dp2#541]
Windows 应用程序日志中有如下信息：

```
Exception information:

    Exception type: ConfigurationErrorsException

    Exception message: Could not load file or assembly 'System.IO.FileSystem.Primitives' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   at System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory()
   at System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai)
   at System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig)
   at System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies()
   at System.Web.Compilation.BuildManager.CallPreStartInitMethods()
   at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)
```

**Comment by DigitalPlatform** [comment]
经检查，发现是因为 dp2 v3 的开发环境(master 分支)切换到分支 v2 时，源代码目录中 dp2installer/opac_app 目录中残余了 v3 的 .dll 文件，分支 v2 编译的时候，copyopac.bat 批处理命令会把 v2 的 .dll 拷贝到上述目录，但遗留下来若干 v3 多出来的 .dll 文件(比如 DigitalPlatform.Core.dll)，这些文件是用 .NET 4.7.2 编译创建的，被打包进入 opac_app.zip 文件，最终被安装到 v2 的 dp2OPAC 的虚拟目录下的 bin 目录中，造成了故障。

解决方法：
0) dp2installer v1 已经更新。
1) 启动 dp2installer，打开 dp2OPAC 的程序文件夹，找到 bin 子目录，手动删除里面的所有 .dll 文件；
2) 启动 dp2installer，升级 dp2installer。若第一步已经自动升级了 dp2installer，则需要用 dp2installer 的菜单 "dp2OPAC/升级 dp2OPAC"再执行一次文件升级。
3) 用 IIS 管理界面，回收 dp2OPAC 应用池，或者干脆重启一次 Windows 操作系统。

**Comment by DigitalPlatform** [comment]
经用户确认问题已在新版本解决。
